// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

/**
 * Build script that:
 * 1. Builds the Vite frontend
 * 2. Reads all files from web/dist/
 * 3. Generates a TypeScript module that exports an in-memory file map
 *
 * This module is imported at compile time so `bun build --compile`
 * embeds everything into the single binary -- same as Rust's include_dir!
 */

import { execSync } from "node:child_process";
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, extname } from "node:path";

const webDir = join(import.meta.dirname, "..", "web");
const distDir = join(webDir, "dist");
const outFile = join(import.meta.dirname, "..", "src", "_embedded_ui.ts");

// 1. Install deps if needed
const nodeModules = join(webDir, "node_modules");
try {
  statSync(nodeModules);
} catch {
  console.log("Installing web dependencies...");
  execSync("bun install", { cwd: webDir, stdio: "inherit" });
}

// 2. Build the frontend
console.log("Building frontend...");
execSync("bun run build", { cwd: webDir, stdio: "inherit" });

// 3. Walk dist/ and collect all files
function walkDir(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...walkDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const files = walkDir(distDir);

// 4. Generate the embedded module
const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
};

let code = `// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

// AUTO-GENERATED by scripts/embed-assets.ts -- do not edit
// This file embeds the compiled web UI into the binary.

export interface EmbeddedFile {
  content: Buffer;
  contentType: string;
  immutable: boolean;
}

const assets = new Map<string, EmbeddedFile>();

`;

for (const file of files) {
  const rel = relative(distDir, file).replace(/\\/g, "/");
  const content = readFileSync(file);
  const b64 = content.toString("base64");
  const ext = extname(file).toLowerCase();
  const mime = MIME_TYPES[ext] ?? "application/octet-stream";
  const immutable = rel !== "index.html";

  code += `assets.set(${JSON.stringify(rel)}, {
  content: Buffer.from(${JSON.stringify(b64)}, "base64"),
  contentType: ${JSON.stringify(mime)},
  immutable: ${immutable},
});\n\n`;
}

code += `export function getEmbeddedFile(path: string): EmbeddedFile | undefined {
  return assets.get(path);
}

export function hasEmbeddedUi(): boolean {
  return assets.size > 0;
}

export { assets as embeddedAssets };
`;

mkdirSync(join(import.meta.dirname, "..", "src"), { recursive: true });
writeFileSync(outFile, code);

console.log(`Embedded ${files.length} files into ${outFile}`);
