// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! MCP Proxy for Custom Tools
//!
//! Provides a lightweight MCP stdio server (written in JavaScript) that runs
//! inside the agent sandbox. It reads custom tool definitions from a JSON
//! config file and forwards tool calls to user-specified webhook URLs via HTTP.
//!
//! Architecture:
//! ```text
//! Claude Code ──stdio MCP──► temps-mcp-proxy (bun script)
//!                                │
//!                                │ HTTP POST
//!                                ▼
//!                     User's webhook endpoint
//! ```
//!
//! The proxy is injected at runtime via `write_file()` — no image rebuild needed.
//! Bun is pre-installed in every sandbox image.

use serde::{Deserialize, Serialize};

/// A custom tool definition that gets exposed via MCP and proxied to a webhook.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomToolDef {
    /// Tool name (must be unique, used as MCP tool name).
    pub name: String,
    /// Human-readable description of what the tool does.
    pub description: String,
    /// JSON Schema for the tool's input parameters.
    pub input_schema: serde_json::Value,
    /// HTTP endpoint to forward tool calls to.
    /// The proxy sends POST with JSON body: `{ "tool": "<name>", "input": { ... } }`
    /// and expects a JSON response: `{ "content": "..." }` or `{ "error": "..." }`
    pub webhook_url: String,
    /// Optional headers to include in the webhook request (e.g. auth tokens).
    /// Supports `${TEMPS_SECRET:name}` placeholders resolved before injection.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
}

/// Config file written to `/home/temps/.temps/custom-tools.json` in the sandbox.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProxyConfig {
    pub tools: Vec<CustomToolDef>,
}

/// Path where the proxy script is installed in the sandbox.
///
/// Lives under `/home/temps/` (the named home volume), NOT `/workspace`.
/// `/workspace` is bind-mounted from the host repo — anything written there
/// would land in the user's git working tree and potentially leak into PRs.
pub const PROXY_SCRIPT_PATH: &str = "/home/temps/.temps/bin/mcp-proxy.mjs";

/// Path where the tool definitions config is written in the sandbox.
pub const PROXY_CONFIG_PATH: &str = "/home/temps/.temps/custom-tools.json";

/// Name used in Claude Code's settings.json mcpServers entry.
pub const MCP_SERVER_NAME: &str = "temps-custom-tools";

/// Generate the mcpServers entry for settings.json.
///
/// Returns a JSON object like:
/// ```json
/// {
///   "temps-custom-tools": {
///     "command": "bun",
///     "args": ["run", "/home/temps/.temps/bin/mcp-proxy.mjs"],
///     "env": {}
///   }
/// }
/// ```
pub fn mcp_server_entry() -> serde_json::Value {
    serde_json::json!({
        MCP_SERVER_NAME: {
            "command": "bun",
            "args": ["run", PROXY_SCRIPT_PATH],
            "env": {}
        }
    })
}

/// The MCP proxy script (JavaScript/Bun).
///
/// This implements a minimal MCP stdio server that:
/// 1. Reads tool definitions from PROXY_CONFIG_PATH
/// 2. Responds to `initialize`, `tools/list`, and `tools/call` JSON-RPC methods
/// 3. Forwards tool calls to the configured webhook URL via HTTP POST
/// 4. Returns the webhook response as MCP tool result content
///
/// Protocol: JSON-RPC 2.0 over stdio, one JSON object per line.
pub const PROXY_SCRIPT: &str = r#"#!/usr/bin/env bun
// temps-mcp-proxy: MCP stdio server that proxies custom tools to webhook endpoints.
// Auto-generated by temps — do not edit.

import { readFileSync } from "fs";
import { createInterface } from "readline";

const CONFIG_PATH = "/home/temps/.temps/custom-tools.json";

let config;
try {
  config = JSON.parse(readFileSync(CONFIG_PATH, "utf-8"));
} catch (e) {
  process.stderr.write(`[mcp-proxy] Failed to read config: ${e.message}\n`);
  process.exit(1);
}

const tools = config.tools || [];

function sendResponse(response) {
  const line = JSON.stringify(response);
  process.stdout.write(line + "\n");
}

function handleInitialize(id) {
  sendResponse({
    jsonrpc: "2.0",
    id,
    result: {
      protocolVersion: "2024-11-05",
      capabilities: { tools: { listChanged: false } },
      serverInfo: { name: "temps-custom-tools", version: "1.0.0" },
    },
  });
}

function handleToolsList(id) {
  sendResponse({
    jsonrpc: "2.0",
    id,
    result: {
      tools: tools.map((t) => ({
        name: t.name,
        description: t.description,
        inputSchema: t.input_schema,
      })),
    },
  });
}

async function handleToolCall(id, params) {
  const toolName = params.name;
  const toolInput = params.arguments || {};
  const toolDef = tools.find((t) => t.name === toolName);

  if (!toolDef) {
    sendResponse({
      jsonrpc: "2.0",
      id,
      result: {
        content: [{ type: "text", text: `Error: unknown tool '${toolName}'` }],
        isError: true,
      },
    });
    return;
  }

  try {
    const headers = { "Content-Type": "application/json", ...(toolDef.headers || {}) };
    const body = JSON.stringify({ tool: toolName, input: toolInput });

    const resp = await fetch(toolDef.webhook_url, {
      method: "POST",
      headers,
      body,
      signal: AbortSignal.timeout(30000),
    });

    const text = await resp.text();

    if (!resp.ok) {
      sendResponse({
        jsonrpc: "2.0",
        id,
        result: {
          content: [{ type: "text", text: `Webhook error (${resp.status}): ${text}` }],
          isError: true,
        },
      });
      return;
    }

    // Try to parse as JSON — if it has a "content" field, use it directly
    let resultText = text;
    try {
      const parsed = JSON.parse(text);
      if (parsed.error) {
        sendResponse({
          jsonrpc: "2.0",
          id,
          result: {
            content: [{ type: "text", text: `Tool error: ${parsed.error}` }],
            isError: true,
          },
        });
        return;
      }
      if (parsed.content) {
        resultText = typeof parsed.content === "string" ? parsed.content : JSON.stringify(parsed.content);
      }
    } catch {
      // Not JSON — use raw text
    }

    sendResponse({
      jsonrpc: "2.0",
      id,
      result: {
        content: [{ type: "text", text: resultText }],
      },
    });
  } catch (e) {
    sendResponse({
      jsonrpc: "2.0",
      id,
      result: {
        content: [{ type: "text", text: `Webhook request failed: ${e.message}` }],
        isError: true,
      },
    });
  }
}

// Handle notifications (no response needed)
function handleNotification(method) {
  if (method === "notifications/initialized") {
    process.stderr.write(`[mcp-proxy] Initialized with ${tools.length} custom tool(s)\n`);
  }
}

const rl = createInterface({ input: process.stdin });

rl.on("line", async (line) => {
  let msg;
  try {
    msg = JSON.parse(line);
  } catch {
    return;
  }

  // Notification (no id) — don't respond
  if (msg.id === undefined || msg.id === null) {
    handleNotification(msg.method);
    return;
  }

  switch (msg.method) {
    case "initialize":
      handleInitialize(msg.id);
      break;
    case "tools/list":
      handleToolsList(msg.id);
      break;
    case "tools/call":
      await handleToolCall(msg.id, msg.params || {});
      break;
    default:
      sendResponse({
        jsonrpc: "2.0",
        id: msg.id,
        error: { code: -32601, message: `Method not found: ${msg.method}` },
      });
  }
});

rl.on("close", () => process.exit(0));
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_proxy_config_serialization() {
        let config = ProxyConfig {
            tools: vec![CustomToolDef {
                name: "get_weather".to_string(),
                description: "Get current weather for a location".to_string(),
                input_schema: serde_json::json!({
                    "type": "object",
                    "properties": {
                        "location": { "type": "string", "description": "City name" }
                    },
                    "required": ["location"]
                }),
                webhook_url: "https://api.example.com/weather".to_string(),
                headers: None,
            }],
        };

        let json = serde_json::to_string_pretty(&config).unwrap();
        let parsed: ProxyConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.tools.len(), 1);
        assert_eq!(parsed.tools[0].name, "get_weather");
    }

    #[test]
    fn test_mcp_server_entry() {
        let entry = mcp_server_entry();
        let server = &entry[MCP_SERVER_NAME];
        assert_eq!(server["command"], "bun");
        assert_eq!(server["args"][0], "run");
        assert_eq!(server["args"][1], PROXY_SCRIPT_PATH);
    }

    #[test]
    fn test_custom_tool_with_headers() {
        let tool = CustomToolDef {
            name: "query_db".to_string(),
            description: "Run a database query".to_string(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "query": { "type": "string" }
                },
                "required": ["query"]
            }),
            webhook_url: "https://api.example.com/query".to_string(),
            headers: Some(
                [(
                    "Authorization".to_string(),
                    "Bearer ${TEMPS_SECRET:db_token}".to_string(),
                )]
                .into_iter()
                .collect(),
            ),
        };

        let json = serde_json::to_string(&tool).unwrap();
        assert!(json.contains("${TEMPS_SECRET:db_token}"));
        let parsed: CustomToolDef = serde_json::from_str(&json).unwrap();
        assert_eq!(
            parsed.headers.unwrap()["Authorization"],
            "Bearer ${TEMPS_SECRET:db_token}"
        );
    }

    #[test]
    fn test_proxy_script_is_valid_js() {
        // Basic sanity: script should start with shebang and contain key functions
        assert!(PROXY_SCRIPT.contains("#!/usr/bin/env bun"));
        assert!(PROXY_SCRIPT.contains("handleInitialize"));
        assert!(PROXY_SCRIPT.contains("handleToolsList"));
        assert!(PROXY_SCRIPT.contains("handleToolCall"));
        assert!(PROXY_SCRIPT.contains("tools/list"));
        assert!(PROXY_SCRIPT.contains("tools/call"));
        assert!(PROXY_SCRIPT.contains("webhook_url"));
    }
}
