// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! ADR-046: extend `log_chunks` for the object-storage chunk format v2.
//!
//! `log_chunks` stays the manifest table — one row per chunk, never per
//! line — but gains the columns the v2 planner (`store::manifest`) needs:
//! a stable `seq` for `line_id` encoding, the footer location so a reader
//! issues exactly one range-GET, a `level_mask` so level filters prune
//! whole chunks, and a `deleted_at` tombstone for the two-phase GC in
//! ADR-046 §8a.3. Nothing here touches `log_chunks` rows written before
//! this migration: every new column defaults such that a v1 row means
//! "format 1, never pruned by level, not deleted".
//!
//! All statements use raw SQL via `execute_unprepared` because
//! `GENERATED ... AS IDENTITY` and partial indexes are not expressible
//! through `sea-orm-migration`'s `ColumnDef`/`Index` builders.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        // `seq` backs `line_id = seq << 20 | line_index` (see
        // `crate::store::LogLineKey`). `GENERATED BY DEFAULT AS IDENTITY`
        // (not ALWAYS) lets a future bulk-import or reconcile-sweep insert an
        // explicit seq recovered from a chunk's own footer, while every
        // ordinary insert still gets one for free. Postgres backfills a
        // sequence and assigns values to existing rows as part of adding an
        // identity column.
        db.execute_unprepared(
            "ALTER TABLE log_chunks ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY",
        )
        .await?;
        db.execute_unprepared(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_log_chunks_seq ON log_chunks (seq)",
        )
        .await?;

        db.execute_unprepared(
            "ALTER TABLE log_chunks \
             ADD COLUMN format_version SMALLINT NOT NULL DEFAULT 1, \
             ADD COLUMN level_mask SMALLINT NOT NULL DEFAULT 31, \
             ADD COLUMN footer_offset BIGINT NULL, \
             ADD COLUMN footer_len INTEGER NULL, \
             ADD COLUMN bloom_len INTEGER NOT NULL DEFAULT 0, \
             ADD COLUMN level_counts INTEGER[] NOT NULL DEFAULT '{}', \
             ADD COLUMN deleted_at TIMESTAMPTZ NULL",
        )
        .await?;

        // Crash-and-replay idempotency (ADR-046 §8a.2): the chunk key is
        // deterministic from `(container_id, first WAL sequence)`, so a
        // retried write re-PUTs the same object and this unique index turns
        // the retried manifest insert into a no-op via `ON CONFLICT DO
        // NOTHING` rather than a duplicate row.
        db.execute_unprepared(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_log_chunks_storage_key \
             ON log_chunks (storage_key)",
        )
        .await?;

        // Planner indexes (ADR-046 §3 step 1). All partial on `deleted_at IS
        // NULL` so a tombstoned chunk — already past its GC grace period or
        // mid-compaction swap — never costs a candidate-scan comparison and
        // never surfaces to a reader. `idx_log_chunks_global_time` (from
        // m20260909_000001) stays as-is: it has no partial predicate and
        // remains useful for admin/GC sweeps that must see tombstoned rows
        // too, so it is not a duplicate of this one.
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_live_ended \
             ON log_chunks (ended_at DESC, id DESC) WHERE deleted_at IS NULL",
        )
        .await?;
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_live_project_ended \
             ON log_chunks (project_id, ended_at DESC) WHERE deleted_at IS NULL",
        )
        .await?;
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_live_external_service_ended \
             ON log_chunks (external_service_id, ended_at DESC) \
             WHERE deleted_at IS NULL AND external_service_id IS NOT NULL",
        )
        .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_live_external_service_ended")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_live_project_ended")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_live_ended")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_storage_key")
            .await?;

        db.execute_unprepared(
            "ALTER TABLE log_chunks \
             DROP COLUMN IF EXISTS deleted_at, \
             DROP COLUMN IF EXISTS level_counts, \
             DROP COLUMN IF EXISTS bloom_len, \
             DROP COLUMN IF EXISTS footer_len, \
             DROP COLUMN IF EXISTS footer_offset, \
             DROP COLUMN IF EXISTS level_mask, \
             DROP COLUMN IF EXISTS format_version",
        )
        .await?;

        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_seq")
            .await?;
        db.execute_unprepared("ALTER TABLE log_chunks DROP COLUMN IF EXISTS seq")
            .await?;

        Ok(())
    }
}
