// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! ADR-046: extend `log_chunks` for the object-storage chunk format v2.
//!
//! `log_chunks` stays the manifest table — one row per chunk, never per
//! line — but gains the columns the v2 planner (`store::manifest`) needs:
//! a stable `seq` for `line_id` encoding, the footer location so a reader
//! issues exactly one range-GET, a `level_mask` so level filters prune
//! whole chunks, and a `deleted_at` tombstone for the two-phase GC in
//! ADR-046 §8a.3. Existing v1 metadata is preserved: every new format
//! column defaults such that a v1 row means "format 1, never pruned by level,
//! not deleted". The new identity `seq` is the sole backfill: Postgres assigns
//! one to every existing row so each legacy chunk can be addressed safely.
//!
//! All statements use raw SQL via `execute_unprepared` because
//! `GENERATED ... AS IDENTITY` and partial indexes are not expressible
//! through `sea-orm-migration`'s `ColumnDef`/`Index` builders.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        // `seq` backs `line_id = seq << 20 | line_index` (see
        // `crate::store::LogLineKey`). `GENERATED BY DEFAULT AS IDENTITY`
        // (not ALWAYS) lets a future bulk-import or reconcile-sweep insert an
        // explicit seq recovered from a chunk's own footer, while every
        // ordinary insert still gets one for free. Postgres backfills a
        // sequence and assigns values to existing rows as part of adding an
        // identity column.
        db.execute_unprepared(
            "ALTER TABLE log_chunks ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY",
        )
        .await?;
        db.execute_unprepared(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_log_chunks_seq ON log_chunks (seq)",
        )
        .await?;

        db.execute_unprepared(
            "ALTER TABLE log_chunks \
             ADD COLUMN format_version SMALLINT NOT NULL DEFAULT 1, \
             ADD COLUMN level_mask SMALLINT NOT NULL DEFAULT 31, \
             ADD COLUMN footer_offset BIGINT NULL, \
             ADD COLUMN footer_len INTEGER NULL, \
             ADD COLUMN bloom_len INTEGER NOT NULL DEFAULT 0, \
             ADD COLUMN level_counts INTEGER[] NOT NULL DEFAULT '{}', \
             ADD COLUMN deleted_at TIMESTAMPTZ NULL",
        )
        .await?;

        // Crash-and-replay idempotency (ADR-046 §8a.2) applies to v2
        // chunks. Legacy v1 rows may legitimately share a storage key while
        // carrying distinct timestamps or sizes, so they must remain
        // untouched and outside this uniqueness constraint.
        db.execute_unprepared(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_log_chunks_storage_key \
             ON log_chunks (storage_key) WHERE format_version >= 2",
        )
        .await?;
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_storage_key_lookup \
             ON log_chunks (storage_key)",
        )
        .await?;

        // Planner indexes (ADR-046 §3 step 1). All partial on `deleted_at IS
        // NULL` so a tombstoned chunk — already past its GC grace period or
        // mid-compaction swap — never costs a candidate-scan comparison and
        // never surfaces to a reader. `idx_log_chunks_global_time` (from
        // m20260909_000001) stays as-is: it has no partial predicate and
        // remains useful for admin/GC sweeps that must see tombstoned rows
        // too, so it is not a duplicate of this one.
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_live_ended \
             ON log_chunks (ended_at DESC, id DESC) WHERE deleted_at IS NULL",
        )
        .await?;
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_live_project_ended \
             ON log_chunks (project_id, ended_at DESC) WHERE deleted_at IS NULL",
        )
        .await?;
        db.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS idx_log_chunks_live_external_service_ended \
             ON log_chunks (external_service_id, ended_at DESC) \
             WHERE deleted_at IS NULL AND external_service_id IS NOT NULL",
        )
        .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_live_external_service_ended")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_live_project_ended")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_live_ended")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_storage_key_lookup")
            .await?;
        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_storage_key")
            .await?;

        db.execute_unprepared(
            "ALTER TABLE log_chunks \
             DROP COLUMN IF EXISTS deleted_at, \
             DROP COLUMN IF EXISTS level_counts, \
             DROP COLUMN IF EXISTS bloom_len, \
             DROP COLUMN IF EXISTS footer_len, \
             DROP COLUMN IF EXISTS footer_offset, \
             DROP COLUMN IF EXISTS level_mask, \
             DROP COLUMN IF EXISTS format_version",
        )
        .await?;

        db.execute_unprepared("DROP INDEX IF EXISTS idx_log_chunks_seq")
            .await?;
        db.execute_unprepared("ALTER TABLE log_chunks DROP COLUMN IF EXISTS seq")
            .await?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sea_orm::{ConnectionTrait, Database, DbBackend, Statement, TransactionTrait};
    use testcontainers::{core::WaitFor, runners::AsyncRunner, GenericImage, ImageExt};

    const LEGACY_SNAPSHOT_SQL: &str = r#"
        SELECT COALESCE(jsonb_agg(to_jsonb(snapshot) ORDER BY snapshot.id), '[]'::jsonb)::text
                   AS snapshot
        FROM (
            SELECT id, project_id, env, service, container_id, deploy_id,
                   started_at, ended_at, storage_key, line_count,
                   compressed_size_bytes, has_errors, line_offsets,
                   node_id, node_name, external_service_id
            FROM log_chunks
        ) AS snapshot
    "#;

    async fn legacy_snapshot(db: &sea_orm::DatabaseConnection) -> String {
        db.query_one(Statement::from_string(
            DbBackend::Postgres,
            LEGACY_SNAPSHOT_SQL,
        ))
        .await
        .expect("query legacy log chunk snapshot")
        .expect("snapshot query returns one row")
        .try_get("", "snapshot")
        .expect("snapshot is JSON text")
    }

    async fn create_legacy_table(db: &sea_orm::DatabaseConnection) {
        db.execute_unprepared(
            r#"
            CREATE TABLE log_chunks (
                id UUID PRIMARY KEY,
                project_id INTEGER NOT NULL,
                env VARCHAR NOT NULL,
                service VARCHAR NOT NULL,
                container_id VARCHAR NOT NULL,
                deploy_id INTEGER,
                started_at TIMESTAMPTZ NOT NULL,
                ended_at TIMESTAMPTZ NOT NULL,
                storage_key VARCHAR NOT NULL,
                line_count INTEGER NOT NULL,
                compressed_size_bytes INTEGER NOT NULL,
                has_errors BOOLEAN NOT NULL DEFAULT FALSE,
                line_offsets INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
                node_id INTEGER,
                node_name VARCHAR,
                external_service_id INTEGER
            );

            CREATE INDEX idx_log_chunks_global_time
                ON log_chunks (ended_at DESC, id DESC);
            "#,
        )
        .await
        .expect("create isolated pre-v2 log_chunks schema");
    }

    async fn seed_legacy_duplicates(db: &sea_orm::DatabaseConnection) {
        db.execute_unprepared(
            r#"
            INSERT INTO log_chunks (
                id, project_id, env, service, container_id, deploy_id,
                started_at, ended_at, storage_key, line_count,
                compressed_size_bytes, has_errors, line_offsets,
                node_id, node_name, external_service_id
            )
            SELECT
                ('00000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
                40 + (i % 3),
                CASE WHEN i % 2 = 0 THEN 'generic-a' ELSE 'generic-b' END,
                'service-' || (i % 4),
                'container-' || i,
                1000 + i,
                TIMESTAMPTZ '2026-01-01 00:00:00+00' + i * INTERVAL '2 seconds',
                TIMESTAMPTZ '2026-01-01 00:00:01+00' + i * INTERVAL '3 seconds',
                'logs/generic/shared.chunk',
                i * 10,
                (ARRAY[128, 256, 512, 1024])[(i % 4) + 1],
                i % 3 = 0,
                ARRAY[0, i * 8, i * 16],
                CASE WHEN i % 2 = 0 THEN 700 + i ELSE NULL END,
                CASE WHEN i % 2 = 0 THEN 'node-' || i ELSE NULL END,
                CASE WHEN i % 5 = 0 THEN 900 + i ELSE NULL END
            FROM generate_series(1, 13) AS rows(i);

            INSERT INTO log_chunks (
                id, project_id, env, service, container_id, deploy_id,
                started_at, ended_at, storage_key, line_count,
                compressed_size_bytes, has_errors, line_offsets,
                node_id, node_name, external_service_id
            )
            SELECT
                ('10000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
                80,
                'generic-c',
                'service-secondary',
                'secondary-' || i,
                NULL,
                TIMESTAMPTZ '2026-02-01 00:00:00+00' + i * INTERVAL '1 minute',
                TIMESTAMPTZ '2026-02-01 00:00:30+00' + i * INTERVAL '1 minute',
                'logs/generic/secondary.chunk',
                i,
                i * 333,
                FALSE,
                ARRAY[i],
                NULL,
                NULL,
                1200
            FROM generate_series(1, 3) AS rows(i);
            "#,
        )
        .await
        .expect("seed duplicate legacy log chunk manifests");
    }

    #[tokio::test]
    async fn test_log_chunks_v2_legacy_duplicates_upgrade_preserves_rows_and_round_trips() {
        let container = match GenericImage::new("postgres", "17-alpine")
            .with_wait_for(WaitFor::message_on_stderr(
                "database system is ready to accept connections",
            ))
            .with_env_var("POSTGRES_PASSWORD", "migration-test")
            .with_startup_timeout(std::time::Duration::from_secs(120))
            .start()
            .await
        {
            Ok(container) => container,
            Err(error) => {
                let message = error.to_string().to_lowercase();
                if message.contains("socket")
                    || message.contains("connection refused")
                    || message.contains("permission denied")
                    || message.contains("docker host")
                    || message.contains("daemon")
                {
                    eprintln!("Skipping log chunks v2 migration test: Docker unavailable: {error}");
                    return;
                }
                panic!("log chunks v2 test database startup failed: {error}");
            }
        };
        let port = container
            .get_host_port_ipv4(5432)
            .await
            .expect("Postgres port");
        let db = Database::connect(format!(
            "postgres://postgres:migration-test@127.0.0.1:{port}/postgres"
        ))
        .await
        .expect("connect to isolated Postgres");
        create_legacy_table(&db).await;
        seed_legacy_duplicates(&db).await;
        let before = legacy_snapshot(&db).await;

        // This is the original migration's uniqueness operation. Prove both
        // that real legacy data rejects it and that its failed transaction can
        // be rolled back without poisoning the migration connection.
        let transaction = db.begin().await.expect("begin old-index transaction");
        let old_index_result = transaction
            .execute_unprepared(
                "CREATE UNIQUE INDEX idx_log_chunks_storage_key_old ON log_chunks (storage_key)",
            )
            .await;
        assert!(
            old_index_result.is_err(),
            "the former full unique index must reject duplicate v1 storage keys"
        );
        transaction
            .rollback()
            .await
            .expect("roll back failed old-index transaction");

        let manager = SchemaManager::new(&db);
        Migration
            .up(&manager)
            .await
            .expect("upgrade duplicate legacy manifests to v2 schema");
        assert_eq!(legacy_snapshot(&db).await, before);

        let sequence_counts = db
            .query_one(Statement::from_string(
                DbBackend::Postgres,
                "SELECT count(*)::bigint AS rows, count(DISTINCT seq)::bigint AS sequences, count(seq)::bigint AS assigned FROM log_chunks",
            ))
            .await
            .expect("query assigned legacy sequences")
            .expect("sequence count row");
        assert_eq!(sequence_counts.try_get::<i64>("", "rows").unwrap(), 16);
        assert_eq!(sequence_counts.try_get::<i64>("", "sequences").unwrap(), 16);
        assert_eq!(sequence_counts.try_get::<i64>("", "assigned").unwrap(), 16);
        let invalid_defaults: i64 = db
            .query_one(Statement::from_string(
                DbBackend::Postgres,
                "SELECT count(*)::bigint AS count FROM log_chunks \
                 WHERE format_version <> 1 OR level_mask <> 31 \
                    OR footer_offset IS NOT NULL OR footer_len IS NOT NULL \
                    OR bloom_len <> 0 OR level_counts <> '{}'::integer[] \
                    OR deleted_at IS NOT NULL",
            ))
            .await
            .expect("query legacy v2-column defaults")
            .expect("legacy default count row")
            .try_get("", "count")
            .expect("legacy invalid-default count");
        assert_eq!(invalid_defaults, 0);

        let indexes = db
            .query_all(Statement::from_string(
                DbBackend::Postgres,
                r#"
                SELECT c.relname AS name, i.indisunique AS is_unique,
                       pg_get_expr(i.indpred, i.indrelid) AS predicate
                FROM pg_index i
                JOIN pg_class c ON c.oid = i.indexrelid
                WHERE c.relname IN (
                    'idx_log_chunks_storage_key',
                    'idx_log_chunks_storage_key_lookup'
                )
                ORDER BY c.relname
                "#,
            ))
            .await
            .expect("inspect storage-key indexes");
        assert_eq!(indexes.len(), 2);
        assert_eq!(
            indexes[0].try_get::<String>("", "name").unwrap(),
            "idx_log_chunks_storage_key"
        );
        assert!(indexes[0].try_get::<bool>("", "is_unique").unwrap());
        let predicate: String = indexes[0].try_get("", "predicate").unwrap();
        assert!(
            predicate.contains("format_version") && predicate.contains(">= 2"),
            "unexpected partial-index predicate: {predicate}"
        );
        assert_eq!(
            indexes[1].try_get::<String>("", "name").unwrap(),
            "idx_log_chunks_storage_key_lookup"
        );
        assert!(!indexes[1].try_get::<bool>("", "is_unique").unwrap());
        assert!(indexes[1]
            .try_get::<Option<String>>("", "predicate")
            .unwrap()
            .is_none());

        db.execute_unprepared(
            r#"
            INSERT INTO log_chunks (
                id, project_id, env, service, container_id, started_at,
                ended_at, storage_key, line_count, compressed_size_bytes,
                has_errors, line_offsets, format_version, deleted_at
            ) VALUES (
                '20000000-0000-0000-0000-000000000001', 200, 'generic-v2',
                'v2-service', 'v2-container', '2026-03-01 00:00:00+00',
                '2026-03-01 00:01:00+00', 'logs/generic/v2.chunk', 2, 2048,
                FALSE, ARRAY[0, 64], 2, '2026-03-02 00:00:00+00'
            )
            "#,
        )
        .await
        .expect("insert tombstoned v2 chunk");
        let retry = db
            .execute_unprepared(
                r#"
                INSERT INTO log_chunks (
                    id, project_id, env, service, container_id, started_at,
                    ended_at, storage_key, line_count, compressed_size_bytes,
                    has_errors, line_offsets, format_version
                ) VALUES (
                    '20000000-0000-0000-0000-000000000002', 200, 'generic-v2',
                    'v2-service', 'v2-retry', '2026-03-01 00:02:00+00',
                    '2026-03-01 00:03:00+00', 'logs/generic/v2.chunk', 3, 4096,
                    FALSE, ARRAY[0], 2
                )
                ON CONFLICT (storage_key) WHERE format_version >= 2 DO NOTHING
                "#,
            )
            .await
            .expect("v2 crash-replay insert resolves through partial unique index");
        assert_eq!(retry.rows_affected(), 0, "tombstones remain unique in v2");

        db.execute_unprepared("DELETE FROM log_chunks WHERE format_version >= 2")
            .await
            .expect("remove v2-only fixture before legacy downgrade comparison");
        Migration
            .down(&manager)
            .await
            .expect("downgrade restored legacy schema");
        assert_eq!(legacy_snapshot(&db).await, before);
        let remaining_v2_columns: i64 = db
            .query_one(Statement::from_string(
                DbBackend::Postgres,
                "SELECT count(*)::bigint AS count FROM information_schema.columns \
                 WHERE table_schema = 'public' AND table_name = 'log_chunks' \
                   AND column_name IN ('seq', 'format_version', 'level_mask', \
                       'footer_offset', 'footer_len', 'bloom_len', \
                       'level_counts', 'deleted_at')",
            ))
            .await
            .expect("inspect downgraded legacy schema")
            .expect("downgraded schema count row")
            .try_get("", "count")
            .expect("remaining v2 column count");
        assert_eq!(remaining_v2_columns, 0);

        Migration
            .up(&manager)
            .await
            .expect("reapply migration over preserved duplicate legacy rows");
        assert_eq!(legacy_snapshot(&db).await, before);
        let reassigned: i64 = db
            .query_one(Statement::from_string(
                DbBackend::Postgres,
                "SELECT count(DISTINCT seq)::bigint AS count FROM log_chunks WHERE seq IS NOT NULL",
            ))
            .await
            .expect("query reassigned sequences")
            .expect("reassigned sequence count row")
            .try_get("", "count")
            .expect("reassigned sequence count");
        assert_eq!(reassigned, 16);

        // Exercise the same migration against an empty legacy table without
        // paying for a second Postgres container.
        Migration
            .down(&manager)
            .await
            .expect("prepare empty-table case");
        db.execute_unprepared("TRUNCATE TABLE log_chunks")
            .await
            .expect("empty legacy log chunks table");
        Migration
            .up(&manager)
            .await
            .expect("upgrade empty legacy table");
        let empty_count: i64 = db
            .query_one(Statement::from_string(
                DbBackend::Postgres,
                "SELECT count(*)::bigint AS count FROM log_chunks",
            ))
            .await
            .expect("query empty upgraded table")
            .expect("empty table count row")
            .try_get("", "count")
            .expect("empty table count");
        assert_eq!(empty_count, 0);
        assert!(manager
            .has_column("log_chunks", "format_version")
            .await
            .expect("inspect empty upgraded table"));
    }
}
