// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

export type HarnessUpgradeCommand = {
  providerId: 'claude_cli' | 'codex_cli' | 'opencode'
  name: string
  command: string
  cliCommand: string
}

const UPGRADE_COMMANDS = [
  {
    providerId: 'claude_cli',
    name: 'Claude Code',
    command: 'claude update && claude --version',
  },
  {
    providerId: 'codex_cli',
    name: 'Codex',
    command:
      'BUN_INSTALL="$HOME/.bun" BUN_INSTALL_BIN="$HOME/.bun/bin" bun add -g @openai/codex@latest && codex --version',
  },
  {
    providerId: 'opencode',
    name: 'OpenCode',
    command: 'opencode upgrade --method curl && opencode --version',
  },
] as const

const SANDBOX_PUBLIC_ID = /^sbx_[0-9a-fA-F]{16}$/

/**
 * Return commands for both the web command console and the local Temps CLI.
 *
 * Sandbox IDs are generated by Temps, but validating here keeps this helper
 * safe if it is ever reused with route input. The remote command is quoted so
 * `$HOME` expands inside the sandbox, never in the operator's local shell.
 */
export function harnessUpgradeCommands(
  sandboxPublicId: string
): HarnessUpgradeCommand[] {
  validateSandboxPublicId(sandboxPublicId)

  return UPGRADE_COMMANDS.map((upgrade) => ({
    ...upgrade,
    cliCommand: `temps sandbox exec ${sandboxPublicId} -- sh -lc ${shellQuote(upgrade.command)}`,
  }))
}

export function sandboxShellCommand(sandboxPublicId: string): string {
  validateSandboxPublicId(sandboxPublicId)
  return `temps sandbox shell ${sandboxPublicId}`
}

function validateSandboxPublicId(sandboxPublicId: string): void {
  if (!SANDBOX_PUBLIC_ID.test(sandboxPublicId)) {
    throw new Error(`Invalid sandbox public ID: ${sandboxPublicId}`)
  }
}

function shellQuote(value: string): string {
  return `'${value.split("'").join(`'\\''`)}'`
}
