// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative } from "node:path";

const webDir = join(import.meta.dirname, "..", "web");
const distDir = join(webDir, "dist");
const outFile = join(import.meta.dirname, "..", "src", "_embedded_ui.ts");

try {
  statSync(join(webDir, "node_modules"));
} catch {
  console.log("Installing web dependencies...");
  execSync("bun install", { cwd: webDir, stdio: "inherit" });
}

console.log("Building Deployment Pulse UI...");
execSync("bun run build", { cwd: webDir, stdio: "inherit" });

function walk(directory: string): string[] {
  return readdirSync(directory).flatMap((entry) => {
    const path = join(directory, entry);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const mimeTypes: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2",
};

let code = `// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

// AUTO-GENERATED by scripts/embed-assets.ts -- do not edit.
import type { EmbeddedFile } from "@temps-sdk/plugin";

const assets = new Map<string, EmbeddedFile>();

`;

for (const file of walk(distDir)) {
  const path = relative(distDir, file).replace(/\\/g, "/");
  const content = readFileSync(file).toString("base64");
  code += `assets.set(${JSON.stringify(path)}, { content: Buffer.from(${JSON.stringify(content)}, "base64"), contentType: ${JSON.stringify(mimeTypes[extname(file)] ?? "application/octet-stream")}, immutable: ${path !== "index.html"} });\n`;
}

code += "\nexport { assets as embeddedAssets };\n";
mkdirSync(join(import.meta.dirname, "..", "src"), { recursive: true });
writeFileSync(outFile, code);
console.log(`Embedded ${walk(distDir).length} files`);
