// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

/**
 * Example Temps plugin built with the Node.js SDK.
 *
 * Demonstrates:
 * - Defining a manifest with navigation entries
 * - Handling HTTP requests with auth context
 * - Querying platform data (projects, deployments)
 * - Subscribing to deployment events
 * - Serving an embedded React web UI
 */

import {
  runPlugin,
  createManifest,
  extractAuthContext,
  type TempsPlugin,
  type PluginContext,
  type PluginEvent,
  type RequestHandler,
  type EmbeddedAssets,
} from "@temps-sdk/plugin";

// Import embedded UI assets (generated by embed-assets.ts at build time)
let embeddedAssets: EmbeddedAssets | undefined;
try {
  const mod = await import("./_embedded_ui.js");
  embeddedAssets = mod.embeddedAssets;
} catch {
  // No embedded assets -- running in dev mode without UI
}

const plugin: TempsPlugin = {
  manifest() {
    return createManifest("hello-node", "0.1.0")
      .displayName("Hello Node")
      .description("Example Node.js plugin demonstrating the SDK")
      .requiresDb(false)
      .addNav("Hello", "hand", "/hello")
      .addNav("Projects", "folder", "/projects")
      .event("deployment.succeeded")
      .event("deployment.failed")
      .build();
  },

  embeddedUiAssets() {
    return embeddedAssets;
  },

  handler(ctx: PluginContext): RequestHandler {
    return async (req, res) => {
      const url = new URL(req.url ?? "/", "http://localhost");
      const auth = extractAuthContext(req);

      switch (url.pathname) {
        case "/hello":
          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(
            JSON.stringify({
              message: `Hello ${auth?.userEmail ?? "anonymous"}!`,
              plugin: ctx.pluginName,
              dataDir: ctx.dataDir,
            })
          );
          break;

        case "/projects": {
          try {
            const projects = await ctx.temps.listProjects();
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(
              JSON.stringify({
                projects: projects.map((p) => ({
                  id: p.id,
                  name: p.name,
                  preset: p.preset,
                  lastDeployment: p.last_deployment,
                })),
              })
            );
          } catch (err) {
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(
              JSON.stringify({
                error: err instanceof Error ? err.message : String(err),
              })
            );
          }
          break;
        }

        case "/deployments": {
          const projectId = url.searchParams.get("project_id");
          if (!projectId) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "project_id is required" }));
            break;
          }
          try {
            const deployments = await ctx.temps.listDeployments(
              parseInt(projectId, 10),
              { limit: 10 }
            );
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ deployments }));
          } catch (err) {
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(
              JSON.stringify({
                error: err instanceof Error ? err.message : String(err),
              })
            );
          }
          break;
        }

        default:
          res.writeHead(404, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Not found" }));
      }
    };
  },

  async onStart(ctx: PluginContext) {
    console.error(`[hello-node] Plugin started! Data dir: ${ctx.dataDir}`);
  },

  onEvent(_ctx: PluginContext, event: PluginEvent) {
    console.error(
      `[hello-node] Received event: ${event.event_type} (project: ${event.project_id})`
    );
  },

  async onShutdown() {
    console.error("[hello-node] Shutting down gracefully");
  },
};

runPlugin(plugin);
