use serde::{Deserialize, Serialize};
use std::fmt;
use utoipa::ToSchema;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, ToSchema)]
pub enum Permission {
    // Project permissions
    ProjectsRead,
    ProjectsWrite,
    ProjectsDelete,
    ProjectsCreate,
    
    // Deployment permissions
    DeploymentsRead,
    DeploymentsWrite,
    DeploymentsDelete,
    DeploymentsCreate,
    
    // Domain permissions
    DomainsRead,
    DomainsWrite,
    DomainsDelete,
    DomainsCreate,
    
    // Environment permissions
    EnvironmentsRead,
    EnvironmentsWrite,
    EnvironmentsDelete,
    EnvironmentsCreate,
    
    // Analytics permissions
    AnalyticsRead,
    AnalyticsWrite,
    
    // User management permissions
    UsersRead,
    UsersWrite,
    UsersDelete,
    UsersCreate,
    
    // System admin permissions
    SystemAdmin,
    SystemRead,
    
    // MCP specific permissions
    McpConnect,
    McpExecute,
    McpRead,
    McpWrite,
    
    // API Key management
    ApiKeysRead,
    ApiKeysWrite,
    ApiKeysDelete,
    ApiKeysCreate,
    
    // Audit permissions
    AuditRead,
    
    // Backup permissions
    BackupsRead,
    BackupsWrite,
    BackupsDelete,
    BackupsCreate,
    
    // Cron permissions
    CronsRead,
    CronsWrite,
    CronsDelete,
    CronsCreate,
    
    // External Services permissions
    ExternalServicesRead,
    ExternalServicesWrite,
    ExternalServicesDelete,
    ExternalServicesCreate,
    
    // Settings permissions
    SettingsRead,
    SettingsWrite,
    
    // Files permissions
    FilesRead,
    FilesWrite,
    FilesDelete,
    FilesUpload,
    
    // Funnel permissions
    FunnelRead,
    FunnelWrite,
    
    // Github permissions
    GithubRead,
    GithubWrite,
    GithubConnect,
    
    // Load Balancer permissions
    LoadBalancerRead,
    LoadBalancerWrite,
    
    // Logs permissions
    LogsRead,
    
    // Metrics permissions
    MetricsRead,
    
    // Notifications permissions
    NotificationsRead,
    NotificationsWrite,
    
    // Notification Preferences permissions
    NotificationPreferencesRead,
    NotificationPreferencesWrite,
    
    // Notification Providers permissions
    NotificationProvidersRead,
    NotificationProvidersWrite,
    NotificationProvidersCreate,
    NotificationProvidersDelete,

    // Pipelines permissions
    PipelinesRead,
    PipelinesWrite,
    PipelinesCreate,
    PipelinesDelete,
    PipelinesExecute,
    
    // Platform Info permissions
    PlatformInfoRead,
    
    // Session Metrics permissions
    SessionMetricsRead,
    
    // Speed Insights permissions
    SpeedInsightsRead,
    
    // Webhooks permissions
    WebhooksRead,
    WebhooksWrite,
    WebhooksCreate,
    WebhooksDelete,
    
    // WebSocket Proxy permissions
    WebSocketProxyConnect,

    // Error Tracking permissions
    ErrorTrackingRead,
    ErrorTrackingWrite,
    ErrorTrackingCreate,

    // Git Provider permissions
    GitProvidersRead,
    GitProvidersWrite,
    GitProvidersCreate,
    GitProvidersDelete,
    GitConnectionsRead,
    GitConnectionsWrite,
    GitConnectionsCreate,
    GitConnectionsDelete,
    GitRepositoriesRead,
    GitRepositoriesSync,

    // Import permissions
    ImportsRead,
    ImportsCreate,
}

impl fmt::Display for Permission {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Permission::ProjectsRead => "projects:read",
            Permission::ProjectsWrite => "projects:write",
            Permission::ProjectsDelete => "projects:delete",
            Permission::ProjectsCreate => "projects:create",
            Permission::DeploymentsRead => "deployments:read",
            Permission::DeploymentsWrite => "deployments:write",
            Permission::DeploymentsDelete => "deployments:delete",
            Permission::DeploymentsCreate => "deployments:create",
            Permission::DomainsRead => "domains:read",
            Permission::DomainsWrite => "domains:write",
            Permission::DomainsDelete => "domains:delete",
            Permission::DomainsCreate => "domains:create",
            Permission::EnvironmentsRead => "environments:read",
            Permission::EnvironmentsWrite => "environments:write",
            Permission::EnvironmentsDelete => "environments:delete",
            Permission::EnvironmentsCreate => "environments:create",
            Permission::AnalyticsRead => "analytics:read",
            Permission::AnalyticsWrite => "analytics:write",
            Permission::UsersRead => "users:read",
            Permission::UsersWrite => "users:write",
            Permission::UsersDelete => "users:delete",
            Permission::UsersCreate => "users:create",
            Permission::SystemAdmin => "system:admin",
            Permission::SystemRead => "system:read",
            Permission::McpConnect => "mcp:connect",
            Permission::McpExecute => "mcp:execute",
            Permission::McpRead => "mcp:read",
            Permission::McpWrite => "mcp:write",
            Permission::ApiKeysRead => "api_keys:read",
            Permission::ApiKeysWrite => "api_keys:write",
            Permission::ApiKeysDelete => "api_keys:delete",
            Permission::ApiKeysCreate => "api_keys:create",
            Permission::AuditRead => "audit:read",
            Permission::BackupsRead => "backups:read",
            Permission::BackupsWrite => "backups:write",
            Permission::BackupsDelete => "backups:delete",
            Permission::BackupsCreate => "backups:create",
            Permission::CronsRead => "crons:read",
            Permission::CronsWrite => "crons:write",
            Permission::CronsDelete => "crons:delete",
            Permission::CronsCreate => "crons:create",
            Permission::ExternalServicesRead => "external_services:read",
            Permission::ExternalServicesWrite => "external_services:write",
            Permission::ExternalServicesDelete => "external_services:delete",
            Permission::ExternalServicesCreate => "external_services:create",
            Permission::FilesRead => "files:read",
            Permission::FilesWrite => "files:write",
            Permission::FilesDelete => "files:delete",
            Permission::FilesUpload => "files:upload",
            Permission::FunnelRead => "funnel:read",
            Permission::FunnelWrite => "funnel:write",
            Permission::GithubRead => "github:read",
            Permission::GithubWrite => "github:write",
            Permission::GithubConnect => "github:connect",
            Permission::LoadBalancerRead => "load_balancer:read",
            Permission::LoadBalancerWrite => "load_balancer:write",
            Permission::LogsRead => "logs:read",
            Permission::MetricsRead => "metrics:read",
            Permission::NotificationsRead => "notifications:read",
            Permission::NotificationsWrite => "notifications:write",
            Permission::NotificationPreferencesRead => "notification_preferences:read",
            Permission::NotificationPreferencesWrite => "notification_preferences:write",
            Permission::NotificationProvidersRead => "notification_providers:read",
            Permission::NotificationProvidersWrite => "notification_providers:write",
            Permission::NotificationProvidersCreate => "notification_providers:create",
            Permission::NotificationProvidersDelete => "notification_providers:delete",
            Permission::PipelinesRead => "pipelines:read",
            Permission::PipelinesWrite => "pipelines:write",
            Permission::PipelinesCreate => "pipelines:create",
            Permission::PipelinesDelete => "pipelines:delete",
            Permission::PipelinesExecute => "pipelines:execute",
            Permission::PlatformInfoRead => "platform_info:read",
            Permission::SessionMetricsRead => "session_metrics:read",
            Permission::SpeedInsightsRead => "speed_insights:read",
            Permission::WebhooksRead => "webhooks:read",
            Permission::WebhooksWrite => "webhooks:write",
            Permission::WebhooksCreate => "webhooks:create",
            Permission::WebhooksDelete => "webhooks:delete",
            Permission::WebSocketProxyConnect => "websocket_proxy:connect",
            Permission::SettingsRead => "settings:read",
            Permission::SettingsWrite => "settings:write",
            Permission::ErrorTrackingRead => "error_tracking:read",
            Permission::ErrorTrackingWrite => "error_tracking:write",
            Permission::ErrorTrackingCreate => "error_tracking:create",
            Permission::GitProvidersRead => "git_providers:read",
            Permission::GitProvidersWrite => "git_providers:write",
            Permission::GitProvidersCreate => "git_providers:create",
            Permission::GitProvidersDelete => "git_providers:delete",
            Permission::GitConnectionsRead => "git_connections:read",
            Permission::GitConnectionsWrite => "git_connections:write",
            Permission::GitConnectionsCreate => "git_connections:create",
            Permission::GitConnectionsDelete => "git_connections:delete",
            Permission::GitRepositoriesRead => "git_repositories:read",
            Permission::GitRepositoriesSync => "git_repositories:sync",
            Permission::ImportsRead => "imports:read",
            Permission::ImportsCreate => "imports:create",
        };
        write!(f, "{}", name)
    }
}

impl Permission {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "projects:read" => Some(Permission::ProjectsRead),
            "projects:write" => Some(Permission::ProjectsWrite),
            "projects:delete" => Some(Permission::ProjectsDelete),
            "projects:create" => Some(Permission::ProjectsCreate),
            "deployments:read" => Some(Permission::DeploymentsRead),
            "deployments:write" => Some(Permission::DeploymentsWrite),
            "deployments:delete" => Some(Permission::DeploymentsDelete),
            "deployments:create" => Some(Permission::DeploymentsCreate),
            "domains:read" => Some(Permission::DomainsRead),
            "domains:write" => Some(Permission::DomainsWrite),
            "domains:delete" => Some(Permission::DomainsDelete),
            "domains:create" => Some(Permission::DomainsCreate),
            "environments:read" => Some(Permission::EnvironmentsRead),
            "environments:write" => Some(Permission::EnvironmentsWrite),
            "environments:delete" => Some(Permission::EnvironmentsDelete),
            "environments:create" => Some(Permission::EnvironmentsCreate),
            "analytics:read" => Some(Permission::AnalyticsRead),
            "analytics:write" => Some(Permission::AnalyticsWrite),
            "users:read" => Some(Permission::UsersRead),
            "users:write" => Some(Permission::UsersWrite),
            "users:delete" => Some(Permission::UsersDelete),
            "users:create" => Some(Permission::UsersCreate),
            "system:admin" => Some(Permission::SystemAdmin),
            "system:read" => Some(Permission::SystemRead),
            "mcp:connect" => Some(Permission::McpConnect),
            "mcp:execute" => Some(Permission::McpExecute),
            "mcp:read" => Some(Permission::McpRead),
            "mcp:write" => Some(Permission::McpWrite),
            "api_keys:read" => Some(Permission::ApiKeysRead),
            "api_keys:write" => Some(Permission::ApiKeysWrite),
            "api_keys:delete" => Some(Permission::ApiKeysDelete),
            "api_keys:create" => Some(Permission::ApiKeysCreate),
            "audit:read" => Some(Permission::AuditRead),
            "backups:read" => Some(Permission::BackupsRead),
            "backups:write" => Some(Permission::BackupsWrite),
            "backups:delete" => Some(Permission::BackupsDelete),
            "backups:create" => Some(Permission::BackupsCreate),
            "crons:read" => Some(Permission::CronsRead),
            "crons:write" => Some(Permission::CronsWrite),
            "crons:delete" => Some(Permission::CronsDelete),
            "crons:create" => Some(Permission::CronsCreate),
            "external_services:read" => Some(Permission::ExternalServicesRead),
            "external_services:write" => Some(Permission::ExternalServicesWrite),
            "external_services:delete" => Some(Permission::ExternalServicesDelete),
            "external_services:create" => Some(Permission::ExternalServicesCreate),
            "settings:read" => Some(Permission::SettingsRead),
            "settings:write" => Some(Permission::SettingsWrite),
            "files:read" => Some(Permission::FilesRead),
            "files:write" => Some(Permission::FilesWrite),
            "files:delete" => Some(Permission::FilesDelete),
            "files:upload" => Some(Permission::FilesUpload),
            "funnel:read" => Some(Permission::FunnelRead),
            "funnel:write" => Some(Permission::FunnelWrite),
            "github:read" => Some(Permission::GithubRead),
            "github:write" => Some(Permission::GithubWrite),
            "github:connect" => Some(Permission::GithubConnect),
            "load_balancer:read" => Some(Permission::LoadBalancerRead),
            "load_balancer:write" => Some(Permission::LoadBalancerWrite),
            "logs:read" => Some(Permission::LogsRead),
            "metrics:read" => Some(Permission::MetricsRead),
            "notifications:read" => Some(Permission::NotificationsRead),
            "notifications:write" => Some(Permission::NotificationsWrite),
            "notification_preferences:read" => Some(Permission::NotificationPreferencesRead),
            "notification_preferences:write" => Some(Permission::NotificationPreferencesWrite),
            "notification_providers:read" => Some(Permission::NotificationProvidersRead),
            "notification_providers:write" => Some(Permission::NotificationProvidersWrite),
            "notification_providers:create" => Some(Permission::NotificationProvidersCreate),
            "notification_providers:delete" => Some(Permission::NotificationProvidersDelete),
            "pipelines:read" => Some(Permission::PipelinesRead),
            "pipelines:write" => Some(Permission::PipelinesWrite),
            "pipelines:create" => Some(Permission::PipelinesCreate),
            "pipelines:delete" => Some(Permission::PipelinesDelete),
            "pipelines:execute" => Some(Permission::PipelinesExecute),
            "platform_info:read" => Some(Permission::PlatformInfoRead),
            "session_metrics:read" => Some(Permission::SessionMetricsRead),
            "speed_insights:read" => Some(Permission::SpeedInsightsRead),
            "webhooks:read" => Some(Permission::WebhooksRead),
            "webhooks:write" => Some(Permission::WebhooksWrite),
            "webhooks:create" => Some(Permission::WebhooksCreate),
            "webhooks:delete" => Some(Permission::WebhooksDelete),
            "websocket_proxy:connect" => Some(Permission::WebSocketProxyConnect),
            "error_tracking:read" => Some(Permission::ErrorTrackingRead),
            "error_tracking:write" => Some(Permission::ErrorTrackingWrite),
            "error_tracking:create" => Some(Permission::ErrorTrackingCreate),
            "git_providers:read" => Some(Permission::GitProvidersRead),
            "git_providers:write" => Some(Permission::GitProvidersWrite),
            "git_providers:create" => Some(Permission::GitProvidersCreate),
            "git_providers:delete" => Some(Permission::GitProvidersDelete),
            "git_connections:read" => Some(Permission::GitConnectionsRead),
            "git_connections:write" => Some(Permission::GitConnectionsWrite),
            "git_connections:create" => Some(Permission::GitConnectionsCreate),
            "git_connections:delete" => Some(Permission::GitConnectionsDelete),
            "git_repositories:read" => Some(Permission::GitRepositoriesRead),
            "git_repositories:sync" => Some(Permission::GitRepositoriesSync),
            "imports:read" => Some(Permission::ImportsRead),
            "imports:create" => Some(Permission::ImportsCreate),
            _ => None,
        }
    }

    pub fn all() -> Vec<Permission> {
        vec![
            Permission::ProjectsRead,
            Permission::ProjectsWrite,
            Permission::ProjectsDelete,
            Permission::ProjectsCreate,
            Permission::DeploymentsRead,
            Permission::DeploymentsWrite,
            Permission::DeploymentsDelete,
            Permission::DeploymentsCreate,
            Permission::DomainsRead,
            Permission::DomainsWrite,
            Permission::DomainsDelete,
            Permission::DomainsCreate,
            Permission::EnvironmentsRead,
            Permission::EnvironmentsWrite,
            Permission::EnvironmentsDelete,
            Permission::EnvironmentsCreate,
            Permission::AnalyticsRead,
            Permission::AnalyticsWrite,
            Permission::UsersRead,
            Permission::UsersWrite,
            Permission::UsersDelete,
            Permission::UsersCreate,
            Permission::SystemAdmin,
            Permission::SystemRead,
            Permission::McpConnect,
            Permission::McpExecute,
            Permission::McpRead,
            Permission::McpWrite,
            Permission::ApiKeysRead,
            Permission::ApiKeysWrite,
            Permission::ApiKeysDelete,
            Permission::ApiKeysCreate,
            Permission::AuditRead,
            Permission::BackupsRead,
            Permission::BackupsWrite,
            Permission::BackupsDelete,
            Permission::BackupsCreate,
            Permission::CronsRead,
            Permission::CronsWrite,
            Permission::CronsDelete,
            Permission::CronsCreate,
            Permission::ExternalServicesRead,
            Permission::ExternalServicesWrite,
            Permission::ExternalServicesDelete,
            Permission::ExternalServicesCreate,
            Permission::SettingsRead,
            Permission::SettingsWrite,
            Permission::FilesRead,
            Permission::FilesWrite,
            Permission::FilesDelete,
            Permission::FilesUpload,
            Permission::FunnelRead,
            Permission::FunnelWrite,
            Permission::GithubRead,
            Permission::GithubWrite,
            Permission::GithubConnect,
            Permission::LoadBalancerRead,
            Permission::LoadBalancerWrite,
            Permission::LogsRead,
            Permission::MetricsRead,
            Permission::NotificationsRead,
            Permission::NotificationsWrite,
            Permission::NotificationPreferencesRead,
            Permission::NotificationPreferencesWrite,
            Permission::NotificationProvidersRead,
            Permission::NotificationProvidersWrite,
            Permission::NotificationProvidersCreate,
            Permission::NotificationProvidersDelete,
            Permission::PipelinesRead,
            Permission::PipelinesWrite,
            Permission::PipelinesCreate,
            Permission::PipelinesDelete,
            Permission::PipelinesExecute,
            Permission::PlatformInfoRead,
            Permission::SessionMetricsRead,
            Permission::SpeedInsightsRead,
            Permission::WebhooksRead,
            Permission::WebhooksWrite,
            Permission::WebhooksCreate,
            Permission::WebhooksDelete,
            Permission::WebSocketProxyConnect,
            Permission::ErrorTrackingRead,
            Permission::ErrorTrackingWrite,
            Permission::ErrorTrackingCreate,
            Permission::GitProvidersRead,
            Permission::GitProvidersWrite,
            Permission::GitProvidersCreate,
            Permission::GitProvidersDelete,
            Permission::GitConnectionsRead,
            Permission::GitConnectionsWrite,
            Permission::GitConnectionsCreate,
            Permission::GitConnectionsDelete,
            Permission::GitRepositoriesRead,
            Permission::GitRepositoriesSync,
            Permission::ImportsRead,
            Permission::ImportsCreate,
        ]
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub enum Role {
    Admin,
    User,
    Reader,
    Mcp,
    ApiReader,
    Custom,  // For API keys with custom permissions
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Role::Admin => "admin",
            Role::User => "user", 
            Role::Reader => "reader",
            Role::Mcp => "mcp",
            Role::ApiReader => "api_reader",
            Role::Custom => "custom",
        };
        write!(f, "{}", name)
    }
}

impl Role {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "admin" => Some(Role::Admin),
            "user" => Some(Role::User),
            "reader" => Some(Role::Reader),
            "mcp" => Some(Role::Mcp),
            "api_reader" => Some(Role::ApiReader),
            "custom" => Some(Role::Custom),
            _ => None,
        }
    }

    pub fn all() -> Vec<Role> {
        vec![
            Role::Admin,
            Role::User,
            Role::Reader,
            Role::Mcp,
            Role::ApiReader,
            Role::Custom,
        ]
    }

    pub fn permissions(&self) -> &'static [Permission] {
        match self {
            Role::Admin => &[
                Permission::AnalyticsRead,
                Permission::AnalyticsWrite,
                Permission::ApiKeysCreate,
                Permission::ApiKeysDelete,
                Permission::ApiKeysRead,
                Permission::ApiKeysWrite,
                Permission::AuditRead,
                Permission::BackupsCreate,
                Permission::BackupsDelete,
                Permission::BackupsRead,
                Permission::BackupsWrite,
                Permission::CronsCreate,
                Permission::CronsDelete,
                Permission::CronsRead,
                Permission::CronsWrite,
                Permission::DeploymentsCreate,
                Permission::DeploymentsDelete,
                Permission::DeploymentsRead,
                Permission::DeploymentsWrite,
                Permission::DomainsCreate,
                Permission::DomainsDelete,
                Permission::DomainsRead,
                Permission::DomainsWrite,
                Permission::EnvironmentsCreate,
                Permission::EnvironmentsDelete,
                Permission::EnvironmentsRead,
                Permission::EnvironmentsWrite,
                Permission::ExternalServicesCreate,
                Permission::ExternalServicesDelete,
                Permission::ExternalServicesRead,
                Permission::ExternalServicesWrite,
                Permission::FilesDelete,
                Permission::FilesRead,
                Permission::FilesUpload,
                Permission::FilesWrite,
                Permission::FunnelRead,
                Permission::FunnelWrite,
                Permission::GithubConnect,
                Permission::GithubRead,
                Permission::GithubWrite,
                Permission::LoadBalancerRead,
                Permission::LoadBalancerWrite,
                Permission::LogsRead,
                Permission::McpConnect,
                Permission::McpExecute,
                Permission::McpRead,
                Permission::McpWrite,
                Permission::MetricsRead,
                Permission::NotificationsRead,
                Permission::NotificationsWrite,
                Permission::NotificationPreferencesRead,
                Permission::NotificationPreferencesWrite,
                Permission::NotificationProvidersCreate,
                Permission::NotificationProvidersDelete,
                Permission::NotificationProvidersRead,
                Permission::NotificationProvidersWrite,
                Permission::PipelinesCreate,
                Permission::PipelinesDelete,
                Permission::PipelinesExecute,
                Permission::PipelinesRead,
                Permission::PipelinesWrite,
                Permission::PlatformInfoRead,
                Permission::ProjectsCreate,
                Permission::ProjectsDelete,
                Permission::ProjectsDelete,
                Permission::ProjectsRead,
                Permission::ProjectsWrite,
                Permission::SessionMetricsRead,
                Permission::SettingsRead,
                Permission::SettingsWrite,
                Permission::SpeedInsightsRead,
                Permission::SystemAdmin,
                Permission::SystemRead,
                Permission::UsersCreate,
                Permission::UsersDelete,
                Permission::UsersRead,
                Permission::UsersWrite,
                Permission::WebSocketProxyConnect,
                Permission::WebhooksCreate,
                Permission::WebhooksDelete,
                Permission::WebhooksRead,
                Permission::WebhooksWrite,
                Permission::ErrorTrackingRead,
                Permission::ErrorTrackingWrite,
                Permission::ErrorTrackingCreate,
                Permission::GitProvidersRead,
                Permission::GitProvidersWrite,
                Permission::GitProvidersCreate,
                Permission::GitProvidersDelete,
                Permission::GitConnectionsRead,
                Permission::GitConnectionsWrite,
                Permission::GitConnectionsCreate,
                Permission::GitConnectionsDelete,
                Permission::GitRepositoriesRead,
                Permission::GitRepositoriesSync,
                Permission::ImportsRead,
                Permission::ImportsCreate,
            ],
            Role::User => &[
                Permission::ProjectsRead,
                Permission::ProjectsWrite,
                Permission::ProjectsCreate,
                Permission::DeploymentsRead,
                Permission::DeploymentsWrite,
                Permission::DeploymentsCreate,
                Permission::DomainsRead,
                Permission::DomainsWrite,
                Permission::DomainsCreate,
                Permission::EnvironmentsRead,
                Permission::EnvironmentsWrite,
                Permission::EnvironmentsCreate,
                Permission::AnalyticsRead,
                Permission::ApiKeysRead,
                Permission::ApiKeysWrite,
                Permission::ApiKeysCreate,
                Permission::AuditRead,
                Permission::BackupsRead,
                Permission::BackupsWrite,
                Permission::BackupsCreate,
                Permission::CronsRead,
                Permission::CronsWrite,
                Permission::CronsCreate,
                Permission::ExternalServicesRead,
                Permission::ExternalServicesWrite,
                Permission::ExternalServicesCreate,
                Permission::FilesRead,
                Permission::FilesWrite,
                Permission::FilesUpload,
                Permission::FunnelRead,
                Permission::FunnelWrite,
                Permission::GithubRead,
                Permission::GithubWrite,
                Permission::GithubConnect,
                Permission::LoadBalancerRead,
                Permission::LoadBalancerWrite,
                Permission::LogsRead,
                Permission::MetricsRead,
                Permission::NotificationsRead,
                Permission::NotificationsWrite,
                Permission::NotificationPreferencesRead,
                Permission::NotificationPreferencesWrite,
                Permission::NotificationProvidersRead,
                Permission::NotificationProvidersWrite,
                Permission::NotificationProvidersCreate,
                Permission::PipelinesRead,
                Permission::PipelinesWrite,
                Permission::PipelinesCreate,
                Permission::PipelinesExecute,
                Permission::PlatformInfoRead,
                Permission::SessionMetricsRead,
                Permission::SpeedInsightsRead,
                Permission::WebhooksRead,
                Permission::WebhooksWrite,
                Permission::WebhooksCreate,
                Permission::WebSocketProxyConnect,
                Permission::ErrorTrackingRead,
                Permission::ErrorTrackingWrite,
                Permission::ErrorTrackingCreate,
                Permission::GitProvidersRead,
                Permission::GitProvidersWrite,
                Permission::GitProvidersCreate,
                Permission::GitConnectionsRead,
                Permission::GitConnectionsWrite,
                Permission::GitConnectionsCreate,
                Permission::GitRepositoriesRead,
                Permission::GitRepositoriesSync,
                Permission::ImportsRead,
                Permission::ImportsCreate,
            ],
            Role::Reader => &[
                Permission::ProjectsRead,
                Permission::DeploymentsRead,
                Permission::DomainsRead,
                Permission::EnvironmentsRead,
                Permission::AnalyticsRead,
                Permission::AuditRead,
                Permission::BackupsRead,
                Permission::CronsRead,
                Permission::ExternalServicesRead,
                Permission::FilesRead,
                Permission::FunnelRead,
                Permission::GithubRead,
                Permission::LoadBalancerRead,
                Permission::LogsRead,
                Permission::MetricsRead,
                Permission::NotificationPreferencesRead,
                Permission::NotificationProvidersRead,
                Permission::PipelinesRead,
                Permission::PlatformInfoRead,
                Permission::SessionMetricsRead,
                Permission::SpeedInsightsRead,
                Permission::WebhooksRead,
                Permission::ErrorTrackingRead,
                Permission::GitProvidersRead,
                Permission::GitConnectionsRead,
                Permission::GitRepositoriesRead,
                Permission::ImportsRead,
            ],
            Role::Mcp => &[
                Permission::ProjectsRead,
                Permission::ProjectsWrite,
                Permission::ProjectsCreate,
                Permission::DeploymentsRead,
                Permission::DeploymentsWrite,
                Permission::DeploymentsCreate,
                Permission::McpConnect,
                Permission::McpExecute,
                Permission::McpRead,
                Permission::McpWrite,
            ],
            Role::ApiReader => &[
                Permission::ProjectsRead,
                Permission::DeploymentsRead,
                Permission::AnalyticsRead,
            ],
            Role::Custom => &[],  // Custom role has no default permissions
        }
    }

    pub fn has_permission(&self, permission: &Permission) -> bool {
        self.permissions().contains(permission)
    }
}