//! Static File Serving
//!
//! Provides HTTP endpoints for serving static files from the configured static directory.
//! Used for screenshots, logs, and other static assets generated by deployments.

pub mod service;
pub mod handler;
pub mod plugin;

pub use service::FileService;
pub use handler::{configure_routes, FileApiDoc};
pub use plugin::StaticFilesPlugin;
