//! Static File Serving
//!
//! Provides HTTP endpoints for serving static files from the configured static directory.
//! Used for screenshots, logs, and other static assets generated by deployments.

pub mod handler;
pub mod plugin;
pub mod service;

pub use handler::{configure_routes, FileApiDoc};
pub use plugin::StaticFilesPlugin;
pub use service::FileService;
