// SPDX-FileCopyrightText: 2024-2026 Temps Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Metadata for environment variables generated by the deployment planner.
//!
//! Project creation uses this module to preview the variables an application
//! will receive without inventing or duplicating that catalog in the frontend.

use serde::{Deserialize, Serialize};
use temps_entities::preset::Preset;
use utoipa::ToSchema;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ManagedEnvironmentVariableSource {
    ErrorTracking,
    OpenTelemetry,
    Temps,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ManagedEnvironmentVariable {
    pub name: String,
    pub source: ManagedEnvironmentVariableSource,
    pub is_secret: bool,
    /// Whether a user-defined value is intentionally allowed to replace the
    /// generated default. When false, the deployment pipeline wins.
    pub is_user_overridable: bool,
    pub description: String,
}

fn variable(
    name: &str,
    source: ManagedEnvironmentVariableSource,
    is_secret: bool,
    is_user_overridable: bool,
    description: &str,
) -> ManagedEnvironmentVariable {
    ManagedEnvironmentVariable {
        name: name.to_string(),
        source,
        is_secret,
        is_user_overridable,
        description: description.to_string(),
    }
}

/// Return the framework-specific public Sentry DSN variable injected for a
/// preset. Backend-only and generic presets use `SENTRY_DSN` only.
pub(crate) fn public_sentry_dsn_var(preset: Preset) -> Option<&'static str> {
    match preset {
        Preset::NextJs => Some("NEXT_PUBLIC_SENTRY_DSN"),
        Preset::Nuxt => Some("NUXT_PUBLIC_SENTRY_DSN"),
        Preset::Vite | Preset::React | Preset::Vue | Preset::SolidStart | Preset::Remix => {
            Some("VITE_SENTRY_DSN")
        }
        Preset::SvelteKit | Preset::Astro | Preset::Rsbuild => Some("PUBLIC_SENTRY_DSN"),
        Preset::Docusaurus => Some("REACT_APP_SENTRY_DSN"),
        Preset::Angular
        | Preset::Python
        | Preset::FastApi
        | Preset::Flask
        | Preset::Django
        | Preset::Rails
        | Preset::Go
        | Preset::Rust
        | Preset::Java
        | Preset::Laravel
        | Preset::NodeJs
        | Preset::Dockerfile
        | Preset::DockerCompose
        | Preset::Nixpacks
        | Preset::Autopack
        | Preset::Static => None,
    }
}

/// Return the public Sentry tunnel variable paired with the preset's public
/// DSN variable.
pub(crate) fn public_sentry_tunnel_var(preset: Preset) -> Option<&'static str> {
    match preset {
        Preset::NextJs => Some("NEXT_PUBLIC_SENTRY_TUNNEL"),
        Preset::Nuxt => Some("NUXT_PUBLIC_SENTRY_TUNNEL"),
        Preset::Vite | Preset::React | Preset::Vue | Preset::SolidStart | Preset::Remix => {
            Some("VITE_SENTRY_TUNNEL")
        }
        Preset::SvelteKit | Preset::Astro | Preset::Rsbuild => Some("PUBLIC_SENTRY_TUNNEL"),
        Preset::Docusaurus => Some("REACT_APP_SENTRY_TUNNEL"),
        Preset::Angular
        | Preset::Python
        | Preset::FastApi
        | Preset::Flask
        | Preset::Django
        | Preset::Rails
        | Preset::Go
        | Preset::Rust
        | Preset::Java
        | Preset::Laravel
        | Preset::NodeJs
        | Preset::Dockerfile
        | Preset::DockerCompose
        | Preset::Nixpacks
        | Preset::Autopack
        | Preset::Static => None,
    }
}

/// Describe every variable the deployment pipeline may provide for a preset.
/// Values are intentionally absent: several entries contain live credentials,
/// and some values do not exist until a deployment is planned.
pub fn managed_environment_variables(preset: Preset) -> Vec<ManagedEnvironmentVariable> {
    use ManagedEnvironmentVariableSource::{ErrorTracking, OpenTelemetry, Temps};

    let mut variables = vec![variable(
        "SENTRY_DSN",
        ErrorTracking,
        false,
        false,
        "Sentry-compatible DSN scoped to the project environment.",
    )];

    variables.push(variable(
        "SENTRY_TUNNEL",
        ErrorTracking,
        false,
        false,
        "Same-origin route used to tunnel error events through Temps.",
    ));

    if let Some(name) = public_sentry_dsn_var(preset) {
        variables.push(variable(
            name,
            ErrorTracking,
            false,
            false,
            "Browser-safe DSN using this framework's public variable prefix.",
        ));
    }
    if let Some(name) = public_sentry_tunnel_var(preset) {
        variables.push(variable(
            name,
            ErrorTracking,
            false,
            false,
            "Same-origin route used by browser SDKs to tunnel error events.",
        ));
    }

    variables.extend([
        variable(
            "SENTRY_RELEASE",
            ErrorTracking,
            false,
            true,
            "Deployment commit, tag, or image version when available.",
        ),
        variable(
            "SENTRY_URL",
            ErrorTracking,
            false,
            true,
            "Base URL used by Sentry-compatible build plugins for source-map uploads.",
        ),
        variable(
            "SENTRY_AUTH_TOKEN",
            ErrorTracking,
            true,
            true,
            "Deployment token used by Sentry-compatible build plugins.",
        ),
        variable(
            "SENTRY_ORG",
            ErrorTracking,
            false,
            true,
            "Organization identifier used by Sentry-compatible build plugins.",
        ),
        variable(
            "SENTRY_PROJECT",
            ErrorTracking,
            false,
            true,
            "Project identifier used by Sentry-compatible build plugins.",
        ),
        variable(
            "TEMPS_API_URL",
            Temps,
            false,
            false,
            "Base URL for APIs exposed to the deployed application.",
        ),
        variable(
            "TEMPS_API_TOKEN",
            Temps,
            true,
            false,
            "Deployment-scoped token for authenticated Temps APIs.",
        ),
        variable(
            "CRON_SECRET",
            Temps,
            true,
            false,
            "Token used to authenticate scheduled HTTP requests.",
        ),
        variable(
            "HOST",
            Temps,
            false,
            true,
            "Default bind address for the deployed application.",
        ),
        variable(
            "TEMPS_ASSET_PREFIX",
            Temps,
            false,
            false,
            "Deployment-specific static asset prefix used to prevent stale chunks.",
        ),
        variable(
            "TEMPS_NODE_NAME",
            Temps,
            false,
            false,
            "Name of the node running this workload replica.",
        ),
        variable(
            "TEMPS_NODE_ID",
            Temps,
            false,
            false,
            "Identifier of the node running this workload replica.",
        ),
        variable(
            "TEMPS_REPLICA",
            Temps,
            false,
            false,
            "One-based replica number for the running container.",
        ),
        variable(
            "OTEL_EXPORTER_OTLP_ENDPOINT",
            OpenTelemetry,
            false,
            false,
            "OpenTelemetry ingestion endpoint for this deployment.",
        ),
        variable(
            "OTEL_EXPORTER_OTLP_PROTOCOL",
            OpenTelemetry,
            false,
            false,
            "Protocol selected for the generated OTLP endpoint.",
        ),
        variable(
            "OTEL_EXPORTER_OTLP_HEADERS",
            OpenTelemetry,
            true,
            false,
            "Authentication and project-routing headers for OTLP exports.",
        ),
        variable(
            "OTEL_SERVICE_NAME",
            OpenTelemetry,
            false,
            false,
            "Service name derived from the project name.",
        ),
        variable(
            "OTEL_SERVICE_VERSION",
            OpenTelemetry,
            false,
            true,
            "Deployment commit, tag, or image version when available.",
        ),
    ]);

    if preset != Preset::DockerCompose {
        variables.push(variable(
            "PORT",
            Temps,
            false,
            false,
            "Container port selected from the project deployment configuration.",
        ));
    }

    if preset == Preset::NextJs {
        variables.push(variable(
            "NEXT_PUBLIC_TEMPS_ASSET_PREFIX",
            Temps,
            false,
            false,
            "Browser-visible deployment asset prefix for Next.js applications.",
        ));
    }

    variables
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nextjs_catalog_contains_framework_specific_and_standard_variables() {
        let names = managed_environment_variables(Preset::NextJs)
            .into_iter()
            .map(|variable| variable.name)
            .collect::<Vec<_>>();

        assert!(names.contains(&"SENTRY_DSN".to_string()));
        assert!(names.contains(&"SENTRY_TUNNEL".to_string()));
        assert!(names.contains(&"NEXT_PUBLIC_SENTRY_DSN".to_string()));
        assert!(names.contains(&"NEXT_PUBLIC_SENTRY_TUNNEL".to_string()));
        assert!(names.contains(&"NEXT_PUBLIC_TEMPS_ASSET_PREFIX".to_string()));
        assert!(names.contains(&"OTEL_EXPORTER_OTLP_ENDPOINT".to_string()));
        assert!(names.contains(&"OTEL_EXPORTER_OTLP_HEADERS".to_string()));
        assert!(!names.contains(&"OTEL_EXPORTER_OTLP_TOKEN".to_string()));
    }

    #[test]
    fn backend_catalog_does_not_invent_a_browser_variable() {
        let names = managed_environment_variables(Preset::Rust)
            .into_iter()
            .map(|variable| variable.name)
            .collect::<Vec<_>>();

        assert!(names.contains(&"SENTRY_DSN".to_string()));
        assert!(names.contains(&"SENTRY_TUNNEL".to_string()));
        assert!(!names.iter().any(|name| name.contains("PUBLIC_SENTRY")));
    }

    #[test]
    fn compose_catalog_does_not_claim_a_global_port() {
        let names = managed_environment_variables(Preset::DockerCompose)
            .into_iter()
            .map(|variable| variable.name)
            .collect::<Vec<_>>();

        assert!(!names.contains(&"PORT".to_string()));
        assert!(names.contains(&"TEMPS_ASSET_PREFIX".to_string()));
    }

    #[test]
    fn only_credentials_are_marked_secret() {
        let variables = managed_environment_variables(Preset::NextJs);
        let secrets = variables
            .into_iter()
            .filter(|variable| variable.is_secret)
            .map(|variable| variable.name)
            .collect::<Vec<_>>();

        assert_eq!(
            secrets,
            vec![
                "SENTRY_AUTH_TOKEN",
                "TEMPS_API_TOKEN",
                "CRON_SECRET",
                "OTEL_EXPORTER_OTLP_HEADERS"
            ]
        );
    }

    #[test]
    fn only_defaults_inserted_with_entry_are_user_overridable() {
        let overridable = managed_environment_variables(Preset::NextJs)
            .into_iter()
            .filter(|variable| variable.is_user_overridable)
            .map(|variable| variable.name)
            .collect::<Vec<_>>();

        assert_eq!(
            overridable,
            vec![
                "SENTRY_RELEASE",
                "SENTRY_URL",
                "SENTRY_AUTH_TOKEN",
                "SENTRY_ORG",
                "SENTRY_PROJECT",
                "HOST",
                "OTEL_SERVICE_VERSION"
            ]
        );
    }
}
