#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Build script that:

1. Builds the Vite frontend (runs bun install + bun run build)
2. Reads all files from web/dist/
3. Generates a Python module (_embedded_ui.py) that exports an in-memory asset map

This module is imported at runtime so PyInstaller embeds everything into the
single binary -- same approach as the Node SDK's embed-assets.ts.
"""

from __future__ import annotations

import base64
import os
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
EXAMPLE_DIR = SCRIPT_DIR.parent
WEB_DIR = EXAMPLE_DIR / "web"
DIST_DIR = WEB_DIR / "dist"
OUT_FILE = EXAMPLE_DIR / "_embedded_ui.py"

MIME_TYPES: dict[str, str] = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".map": "application/json",
    ".txt": "text/plain; charset=utf-8",
}


def run(cmd: list[str], cwd: Path) -> None:
    """Run a command, streaming output."""
    print(f"  > {' '.join(cmd)}")
    subprocess.check_call(cmd, cwd=str(cwd))


def walk_files(directory: Path) -> list[Path]:
    """Recursively walk a directory and return all file paths."""
    files: list[Path] = []
    for root, _dirs, filenames in os.walk(directory):
        for name in filenames:
            files.append(Path(root) / name)
    return sorted(files)


def main() -> None:
    # 1. Install deps if needed
    node_modules = WEB_DIR / "node_modules"
    if not node_modules.exists():
        print("Installing web dependencies...")
        run(["bun", "install"], cwd=WEB_DIR)

    # 2. Build the frontend
    print("Building frontend...")
    run(["bun", "run", "build"], cwd=WEB_DIR)

    if not DIST_DIR.exists():
        print(f"ERROR: {DIST_DIR} not found after build", file=sys.stderr)
        sys.exit(1)

    # 3. Walk dist/ and collect all files
    files = walk_files(DIST_DIR)
    if not files:
        print(f"ERROR: No files found in {DIST_DIR}", file=sys.stderr)
        sys.exit(1)

    # 4. Generate the embedded module
    lines: list[str] = [
        "# SPDX-FileCopyrightText: 2024-2026 Temps Contributors",
        "# SPDX-License-Identifier: MIT OR Apache-2.0",
        "",
        '"""AUTO-GENERATED by scripts/embed_assets.py -- do not edit.',
        "",
        "This file embeds the compiled web UI into the binary.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from temps_plugin.types import EmbeddedAssets, EmbeddedFile",
        "",
        "embedded_assets: EmbeddedAssets = {}",
        "",
    ]

    for file_path in files:
        rel = file_path.relative_to(DIST_DIR).as_posix()
        content = file_path.read_bytes()
        b64 = base64.b64encode(content).decode("ascii")
        ext = file_path.suffix.lower()
        mime = MIME_TYPES.get(ext, "application/octet-stream")
        immutable = rel != "index.html"

        lines.append(f"embedded_assets[{rel!r}] = EmbeddedFile(")
        lines.append(f"    content=__import__('base64').b64decode({b64!r}),")
        lines.append(f"    content_type={mime!r},")
        lines.append(f"    immutable={immutable},")
        lines.append(")")
        lines.append("")

    OUT_FILE.write_text("\n".join(lines))
    print(f"Embedded {len(files)} files into {OUT_FILE}")


if __name__ == "__main__":
    main()
